apiVersion: v1
baseDomain: ocpgcp.davoscar.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocpgcpcl
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    network: vpctestocp
    controlPlaneSubnet: subnet1
    computeSubnet: subnet1
    projectID: testocp-2
    region: us-east1
publish: Internal
fips: false
pullSecret: 
sshKey: |
